# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fdac08a1d94ac54c8d16186e751e9aed34561ad0981faf12b81244ef101a5f99171e6473d1b5215f5ef3e19e99293cedbabc92784cf7b8a257c69a95d57bcf7

test:
  secret_key_base: d96045ed985696276f36ad101de2a964ee7d7b3c1011b6abd461cbb62dedb87a64016c0f637f643685af8e007ab420ef4476e22c3ffaada3f3f169b8b00312f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
